<?php

namespace AppBundle\Repository;

/**
 * CouleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouleurRepository extends \Doctrine\ORM\EntityRepository
{    
    public function getRandomEntity()
    {
        return  $this->createQueryBuilder('t')
            ->addSelect('RAND() as HIDDEN rand')
            ->addOrderBy('rand')
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }
}
