<?php

namespace AppBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRandomEntity($exclude_id = null)
    {
        $qb = $this->createQueryBuilder('i')
            ->addSelect('RAND() as HIDDEN rand')
            ->addOrderBy('rand')
            ->andWhere('i.isDisabled = :disabled')
            ->setParameter('disabled', false)
            ->setMaxResults(1);  
                
        if($exclude_id) {
            $qb->andWhere('i.id <> :id')
                ->setParameter('id', $exclude_id);
        }        
        return $qb->getQuery()
            ->getOneOrNullResult();
        
    }    
}
