<?php

namespace AppBundle\Repository;

/**
 * RepereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepereRepository extends \Doctrine\ORM\EntityRepository
{
}
