<?php

namespace AppBundle\Repository;

/**
 * TexteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TexteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRandomEntity()
    {
        return  $this->createQueryBuilder('t')
            ->addSelect('RAND() as HIDDEN rand')
            ->addOrderBy('rand')
            ->getQuery()
            ->getOneOrNullResult();
    }
    
    public function getSecondRandomEntity($auteur)
    {
        return  $this->createQueryBuilder('t')
            ->addSelect('RAND() as HIDDEN rand')
            ->addOrderBy('rand')
                ->where('t.auteur <> :auteur')
            ->setParameter('auteur', $auteur)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
